SET NOCOUNT ON
DECLARE @input varchar(max) = N'"\"qxfcsmh\""
"\"ffsfyxbyuhqkpwatkjgudo\""
"\"byc\\x22yxuafof\\\\\\x22uf\\\\axfozomj\\\\olh\\x22\""
"\"jtqvz\""
"\"uzezxa\\\"jgbmojtwyfbfguz\""
"\"vqsremfk\\x22xiknektafj\""
"\"wzntebpxnnt\\\"vqndz\\\"i\\x22vvjqo\\\"\""
"\"higvez\\\"k\\\"riewqk\""
"\"dlkrbhbrlfrp\\\\damiauyucwhty\""
"\"d\\\"\""
"\"qlz\""
"\"ku\""
"\"yy\\\"\\\"uoao\\\"uripabop\""
"\"saduyrntuswlnlkuppdro\\\\sicxosted\""
"\"tj\""
"\"zzphopswlwdhebwkxeurvizdv\""
"\"xfoheirjoakrpofles\\\"nfu\""
"\"q\\x22oh\\\"p\\x22\\\"n\""
"\"qeendp\\\"ercwgywdjeylxcv\""
"\"dcmem\""
"\"\\\"i\\x22r\\\"l\""
"\"ikso\\x22bvqnbrjduh\\\"uqudzki\\x22rwk\""
"\"wfdsn\""
"\"pwynglklryhtsqbno\""
"\"hcoj\\x22iccz\\\"v\\\"ttr\""
"\"zf\\x22\\\\hlj\\\\kkce\\\\d\\\\asy\\\"yyfestwcdxyfj\""
"\"xs\""
"\"m\\\"tvltapxdvtrxiy\""
"\"bmud\""
"\"k\\\"a\""
"\"b\\\"oas\""
"\"\\\"yexnjjupoqsxyqnquy\\\"uzfdvetqrc\""
"\"vdw\\x22olxfgujaj\""
"\"qomcxdnd\\\"\\\\cfoe\\\"\""
"\"fpul\""
"\"m\\\"avamefphkpv\""
"\"vvdnb\\\\x\\\\uhnxfw\\\"dpubfkxfmeuhnxisd\""
"\"hey\\\\\""
"\"ldaeigghlfey\""
"\"eure\\\"hoy\\x22iezjp\\\\tm\""
"\"yygb\\\"twbj\\\\r\\\"\\x22gmxuhmp\\\"\""
"\"weirebp\\x22mqonbtmfmd\""
"\"ltuz\\\\hs\\\"e\""
"\"ysvmpc\""
"\"g\\x22mjtt\\\"megl\\\"omsaihifwa\""
"\"yimmm\""
"\"iiyqfalh\""
"\"cwknlaaf\""
"\"q\\x22feg\\x22s\\\"xx\""
"\"uayrgeurgyp\\\\oi\""
"\"xhug\\\"pt\\\"axugllbdiggzhvy\""
"\"kdaarqmsjfx\\x22d\""
"\"\\\"vkwla\""
"\"d\\\"\""
"\"tmroz\\\"bvfinxoe\\\\mum\\\"wmm\""
"\"\\\"n\\\"bbswxne\\\\p\\\\yr\\\"qhwpdd\""
"\"skzlkietklkqovjhvj\\x22\""
"\"pbg\\\\pab\\\"bubqaf\\\"obzcwxwywbs\\\\dhtq\""
"\"xxjidvqh\\\"lx\\\\wu\\\"ij\""
"\"daef\\x22e\\x22\\\\kbeeb\\x22qnydtboof\""
"\"ogvazaqy\\\"j\\x22\""
"\"y\""
"\"n\\\"tibetedldy\\\\gsamm\\\"nwu\""
"\"wldkvgdtqulwkad\""
"\"dpmxnj\""
"\"twybw\\\"cdvf\\\"mjdajurokbce\""
"\"ru\\\"\\\\lasij\\\"i\""
"\"roc\\\\vra\\\\lhrm\""
"\"pbkt\\x22booz\\\"fjlkc\""
"\"j\\x22ytvjwrzt\""
"\"\\\\uiwjkniumxcs\""
"\"cbhm\\\"nexccior\\\"v\\\"j\\\"nazxilmfp\\x22\""
"\"qdxngevzrlgoq\""
"\"\\\"lrzxftytpobsdfyrtdqpjbpuwmm\\x22\""
"\"mdag\\x22snck\\x22ggj\\\"slb\\\"fjy\""
"\"wyqkhjuazdtcgkcxvjkpnjdae\""
"\"aixfk\\x22iom\\x22vueob\""
"\"dkiiakyjpkffqlluhaetires\""
"\"ysspv\\\"lysgkvnmwbbsy\""
"\"gy\\\"ryexcjjxdm\\\"xswssgtr\""
"\"s\""
"\"ddxv\""
"\"qwt\\\"\\x22puilb\\\"pslmbrsxhrz\""
"\"qdg\\x22e\\\\qwtknlvkol\\x22oqvmchn\\\\\""
"\"lvo\""
"\"b\""
"\"fk\\\"aa\\\"\\\"yenwch\\\\\\\\on\""
"\"srig\\x22hpwaavs\\\\\\x22qzk\\\"xa\\\"\\x22u\\\\wr\""
"\"yxjxuj\\\"ghyhhxfj\\\"\\x22qvatre\""
"\"yoktqxjxkzrklkoeroil\""
"\"\\\"jfmik\\\"\""
"\"smgseztzdwldikbqrh\\\"\""
"\"jftahgctf\\\"hoqy\""
"\"tcnhicr\\\"znpgckt\\\"ble\""
"\"vqktnkodh\\\"lo\\\"a\\\\bkmdjqqnsqr\""
"\"ztnirfzqq\""
"\"s\""
"\"xx\""
"\"iqj\\\"y\\\\hqgzflwrdsusasekyrxbp\\\\ad\""
"\"\\\\xzjhlaiynkioz\\\"\\\"bxepzimvgwt\""
"\"s\\x22rbw\""
"\"mniieztwrisvdx\""
"\"atyfxioy\\x22\\\\\""
"\"irde\\x22\\x22vbah\\\\jekw\\\"ia\""
"\"bdmftlhkwrprmpat\\\"prfaocvp\""
"\"w\\\\k\""
"\"umbpausy\""
"\"zfauhpsangy\""
"\"p\\\"zqyw\""
"\"wtztypyqvnnxzvlvipnq\\\"zu\""
"\"deicgwq\\\\oqvajpbov\\\\or\\\"kgplwu\""
"\"mbzlfgpi\\\\\\\\zqcidjpzqdzxityxa\""
"\"lfkxvhma\""
"\"\\x22yduqzqr\\\"\\\\fak\\\"p\\\"n\""
"\"mpajacfuxotonpadvng\""
"\"anb\\\\telzvcdu\\\\a\\x22flfq\""
"\"lrs\\\"ebethwpmuuc\\\"\\x22ygr\""
"\"qmvdbhtumzc\\\"ci\""
"\"meet\""
"\"yopg\\x22dxdq\\\"h\\\\ugsu\\x22molxjv\""
"\"uhy\""
"\"fzgidrtzycsireghazscvmwcfmw\\\\t\""
"\"cqohkhpgvpru\""
"\"bihyigtnvmevx\\\"xx\""
"\"xz\""
"\"zofomwotzuxsjk\\\"q\\\"mc\\\"js\\\"dnmalhxd\""
"\"\\\\ktnddux\\\\fqvt\\\"ibnjntjcbn\""
"\"ia\""
"\"htjadnefwetyp\\x22kbrwfycbyy\""
"\"\\\"\\\\hkuxqddnao\""
"\"meqqsz\\x22luecpgaem\""
"\"cvks\\x22frvxo\\\"svqivqsdpgwhukmju\""
"\"sgmxiai\\\\o\\\"riufxwjfigr\\x22\""
"\"fgywdfecqufccpcdn\""
"\"faghjoq\\x22abxnpxj\""
"\"zuppgzcfb\\\"dctvp\\\"elup\\\"zxkopx\""
"\"xqs\\x22xxdqcihbwghmzoa\""
"\"anbnlp\\\\cgcvm\\\"hc\""
"\"xf\\\"fgrngwzys\""
"\"nrxsjduedcy\\x22\""
"\"\\x22sxl\\\"gj\\\"sds\\\"ulcruguz\\\\t\\\\ssvjcwhi\""
"\"jhj\\\"msch\""
"\"qpovolktfwyiuyicbfeeju\\x22\""
"\"nkyxmb\\\"qyqultgt\\\"nmvzvvnxnb\""
"\"ycsrkbstgzqb\\\"uv\\\\cisn\""
"\"s\""
"\"ueptjnn\\\"\\\"sh\""
"\"lp\\\"z\\\"d\\\"mxtxiy\""
"\"yzjtvockdnvbubqabjourf\\\"k\\\"uoxwle\""
"\"\\x22\\\"wqm\\\"\""
"\"\\x22cwtuks\\x22pgh\""
"\"wd\""
"\"tbvf\""
"\"ttbmzdgn\""
"\"vfpiyfdejyrlbgcdtwzbnm\""
"\"uc\""
"\"otdcmhpjagqix\""
"\"\\\\\\x22qso\\\"s\""
"\"scowax\""
"\"behpstjdh\\x22qlgnqjyz\\\"eesn\""
"\"r\\x22cbnjwzveoomkzlo\\\\kxlfouhm\""
"\"jgrl\""
"\"kzqs\\\\r\""
"\"ctscb\\x22thwkdyko\\\"\\x22pkf\\\"d\\x22knmhurg\""
"\"tc\\\"kw\\x22tt\""
"\"bxb\\x22cl\""
"\"jyrmfbphsldwpq\""
"\"jylpvysl\\\"\\\"juducjg\""
"\"en\\\\m\\\"kxpq\\\"wpb\\\\\\\"\""
"\"madouht\\\"bmdwvnyqvpnawiphgac\\\"\""
"\"vuxpk\\\"ltucrw\""
"\"aae\\x22arr\""
"\"ttitnne\\\"kilkrgssnr\\x22urzh\""
"\"oalw\""
"\"pc\\\"\\\"gktkdykzbdpkwigucqni\\\"nxiqx\""
"\"dbrsaj\""
"\"bgzsowyxcbrvhtvekhsh\\\"qgd\""
"\"kudfemvk\\\"\\\"\\\"hkbrbil\\\"chkqoa\""
"\"zjzgj\\\\ekbhyfzufy\""
"\"\\\\acos\\\"fqekuxqzxbmkbnn\\x22jzwrm\""
"\"elxahvudn\\\"txtmomotgw\""
"\"\\x22oxmwdhelpr\\\"cgi\\x22pzvb\""
"\"eapheklx\""
"\"hfvma\\\"mietvc\\\"tszbbm\\\"czex\""
"\"h\\\"iiockj\\\\\\x22et\""
"\"d\\\"rmjjftm\""
"\"qlvhdcbqtyrhlc\\\\\""
"\"yy\\\"rsucjtulm\\\"coryri\\\"eqjlbmk\""
"\"tv\""
"\"r\\\"bfuht\\\\jjgujp\\\"\""
"\"kukxvuauamtdosngdjlkauylttaokaj\""
"\"srgost\\\"\\\"rbkcqtlccu\\x22ohjptstrjkzy\""
"\"yxwxl\\\\yjilwwxffrjjuazmzjs\""
"\"dxlw\\\\fkstu\\\"hjrtiafhyuoh\\\"sewabne\""
"\"\\x22sj\\\"v\""
"\"rfzprz\\x22\\\"oxqclu\\\"krzefp\\\\q\""
"\"cfmhdbjuhrcymgxpylllyvpni\""
"\"ucrmjvmimmcq\\x22\\x22\\\"lz\""
"\"lujtt\\\"\""
"\"gvbqoixn\\\"pmledpjmo\\\"flydnwkfxllf\""
"\"dvxqlbshhmelsk\\x22ig\\\"l\""
"\"mx\\x22lma\\x22bguxejg\""
"\"\\x22jdati\\x22eieo\""
"\"\\\"iyyupixei\\x22ff\""
"\"xohzf\\\"rbxsoksxamiu\""
"\"vlhthspeshzbppa\\x22rhqnohjop\\\"\\\"mfjd\""
"\"f\\\"tvxxla\\\"vurian\\\"\\\"idjq\\x22ptm\\x22olep\""
"\"gzqz\""
"\"kbq\\\\wogye\\\\altvi\\\\hbvmodny\""
"\"j\\x22\""
"\"ofjozdhkblvndl\""
"\"hbitoupimbawimxlxqze\""
"\"ypeleimnme\""
"\"xfwdrzsc\\\\oxqamawyizvi\\\\y\""
"\"enoikppx\\x22ixe\\\"yo\\\"gumye\""
"\"fb\""
"\"vzf\""
"\"zxidr\""
"\"cu\\x22beirsywtskq\""
"\"lxpjbvqzztafwezd\""
"\"\\\\jyxeuo\\x22bv\""
"\"b\\\"vawc\\\"p\\\\\\\\giern\\\"b\""
"\"odizunx\\\"\\\"t\\\\yicdn\\\"x\\\"sdiz\""
"\"\\\"\\\"tebrtsi\""
"\"ctyzsxv\\x22pegfkwsi\\\"tgyltaakytccb\""
"\"htxwbofchvmzbppycccliyik\\x22a\""
"\"ggsslefamsklezqkrd\""
"\"rcep\\\"fnimwvvdx\\\"l\""
"\"zyrzlqmd\\x22egvqs\\\\llqyie\""
"\"\\x22gsqyrr\\\\rcyhyspsvn\""
"\"butg\\\"\""
"\"gb\""
"\"gywkoxf\\\"jsg\\\\wtopxvumirqxlwz\""
"\"rj\\\"ir\\\"wldwveair\\x22s\\\"dhjrdehbqnzl\""
"\"ru\\\"elktnsbxufk\\\\ejufjfjlevt\\\\lrzd\""
"\"\\\"widsvok\""
"\"oy\\\"\\x22nuesvw\""
"\"ay\""
"\"syticfac\\x22fjsivwlmy\\\"pumsqlqqzx\""
"\"m\""
"\"rjjkfh\\x22cf\\x22rgceg\\\"jmdyas\\\"\\\\xlv\\x22p\""
"\"tmuvo\\\"\\x22fdqdovjmdmkgpstotojkv\\\"as\""
"\"jd\\\\ojvynhxllfzzxvbn\\\"wrpphcvx\""
"\"pz\""
"\"\\\"twr\""
"\"n\\\\hdzmxe\\\"mzjjeadlz\""
"\"fb\\\"rprxuagvahjnri\""
"\"rfmexmjjgh\\\\xrnmyvnatrvfruflaqjnd\""
"\"obbbde\\\"co\\\"qr\\\"qpiwjgqahqm\\\\jjp\\\"\""
"\"vpbq\\\"\\\"y\\\"czk\\\\b\\x22ed\\\"lnzepobp\""
"\"syzeajzfarplydipny\\\"y\\\"\\x22ad\""
"\"mpyodwb\""
"\"\\x22rakphlqqptd\""
"\"wa\\\"oj\\\"aiy\""
"\"a\""
"\"ropozx\""
"\"q\\x22nbtlwa\""
"\"etukvgx\\\\jqxlkq\""
"\"\\\"tp\\\"rah\\\"pg\\\"s\\\"bpdtes\\\\tkasdhqd\""
"\"dn\\\"qqpkikadowssb\\x22h\\\"dzpsf\\\\ect\\\"jdh\""
"\"pxunovbbrrn\\\\vullyn\\\"bno\\\"\\\"\\\"myfxlp\\\"\""
"\"qaixyazuryvkmoulhcqaotegfj\\\\mpzm\""
"\"bvfrbicutzbjwn\\\\oml\\\"cf\\\"d\\\"ezcpv\\\"j\""
"\"rmbrdtneudemigdhelmb\""
"\"aq\\\\aurmbhy\""
"\"wujqvzw\""
"\"gf\\\"tssmvm\\\"gm\\\"hu\\x22\\x22yjawsa\""
"\"hrhqqxow\\x22gsydtdspcfqy\\\"zw\\\\ou\""
"\"ianwwf\\\\yko\\\\tdujhhqdi\""
"\"xylz\\\"zpvpab\""
"\"lwuopbeeegp\""
"\"aoop\\x22jhhcexdmdtun\""
"\"\\\\\\\\mouqqcsgmz\""
"\"tltuvwhveau\\x22b\\\"ymxjlcgiymcynwt\""
"\"gsugerumpyuhtjljbhrdyoj\""
"\"lnjm\\x22wg\\\"ajh\""
"\"zmspue\\\"nfttdon\\\\b\\\"eww\""
"\"\\\"w\\x22jwaq\\x22rnmyvs\\\\rmdsuwydsd\\\"th\""
"\"ogtgvtlmcvgllyv\""
"\"z\\\"fqi\\\"rvddoehrciyl\""
"\"yustxxtot\\\"muec\\\"xvfdbzunzvveq\""
"\"mqslw\""
"\"txqnyvzmibqgjs\\x22xy\\x22nfalfyx\""
"\"kzhehlmkholov\""
"\"plpmywcnirrjutjguosh\\\\\""
"\"pydbnqofv\\\"dn\\\\m\""
"\"aegqof\""
"\"eambmxt\\\\dxagoogl\\\\zapfwwlmk\""
"\"afbmqitxxqhddlozuxcpjxgh\""
"\"vgts\""
"\"bfdpqtoxzzhmzcilehnflna\""
"\"s\\\"idpz\""
"\"\\x22hgly\\\"nlmztwybx\\\"ecezmsxaqw\""
"\"aackfgndqcqiy\""
"\"\\x22unqdlsrvgzfaohoffgxzfpir\\\"s\""
"\"abh\\\"ydv\\\"kbpdhrerl\""
"\"bdzpg\""
"\"ekwgkywtmzp\""
"\"wtoodejqmrrgslhvnk\\\"pi\\\"ldnogpth\""
"\"njro\\x22qgbx\\x22af\\\"\\\\suan\""
'

DECLARE @KeepValues varchar(200)
SET @KeepValues = ISNULL(@KeepValues,'a-z0-9\"')
SET @KeepValues = '%[^'+ @KeepValues + ']%'


DECLARE @expression varchar(500)
       ,@expressionDataLength int 
       ,@charCount  int
DECLARE @ExpressionList TABLE (expression nvarchar(500) , lenght int , charCount int)

WHILE CHARINDEX(CHAR(13),@input,0) > 0 BEGIN
    SET @expression = RTRIM(LTRIM(LEFT(@input,CHARINDEX(CHAR(13),@input,0)-1)))
    SET @input = STUFF(@input,1,CHARINDEX(CHAR(13),@input,0),'')

    WHILE PatIndex(@KeepValues, @expression) > 0 SET @expression = Stuff(@expression, PatIndex(@KeepValues, @expression), 1, '')

    SET  @expressionDataLength = DATALENGTH(@expression)
    
    WHILE PATINDEX('%[\][\]%',@expression) > 0 SET @expression = STUFF(@expression,PATINDEX('%[\][\]%',@expression),2,'.')
    WHILE PATINDEX('%[\]["]%',@expression) > 0 SET @expression = STUFF(@expression,PATINDEX('%[\]["]%',@expression),2,'#')
    WHILE PATINDEX('%[\]x%',@expression) > 0 SET @expression = STUFF(@expression,PATINDEX('%[\]x%',@expression),4,'*')
    
    SET @charCount = DATALENGTH(@expression) - 2     
    INSERT INTO @ExpressionList (expression,lenght,charCount)
    SELECT @expression ,@expressionDataLength,@charCount
    
END



SELECT Sum(el.lenght) , sum(el.charCount) FROM @ExpressionList el

SELECT Sum(el.lenght) - sum(el.charCount) FROM @ExpressionList el

SELECT * FROM @ExpressionList



